/// A candidate reminder produced by the AI assistant before the user
/// confirms it.
///
/// Intentionally separate from [Reminder]: `id` is a local UUID used as
/// the review-row key (not the microseconds-since-epoch used for
/// persistence), the time is mutable in the review UI, and `selected`
/// lives here, not on the persistent model.
class ReminderDraft {
  ReminderDraft({
    required this.id,
    required this.title,
    required this.suggestedTime,
    this.reason,
    this.description,
    this.selected = true,
  });

  /// Stable per-row key. Generated by the analyzer as a fresh UUID4.
  final String id;

  /// User-visible title. Mutable so the review UI can edit in place.
  String title;

  /// Proposed fire time. Mutable so the user can adjust via a date+time
  /// picker before saving.
  DateTime suggestedTime;

  /// Optional one-line rationale from the model. Shown as a subtitle in
  /// the review row.
  String? reason;

  /// Optional multi-line body. Mirrors [Reminder.description] so drafts
  /// parsed by the AI assistant can carry a body the same way manual
  /// reminders do. Populated when the AI response includes a
  /// `description` field for the reminder; otherwise `null`.
  String? description;

  /// Whether this draft should be saved when the user taps the bulk
  /// "添加" button. Defaults to `true`.
  bool selected;

  ReminderDraft copyWith({
    String? title,
    DateTime? suggestedTime,
    String? reason,
    String? description,
    bool? selected,
  }) {
    return ReminderDraft(
      id: id,
      title: title ?? this.title,
      suggestedTime: suggestedTime ?? this.suggestedTime,
      reason: reason ?? this.reason,
      description: description ?? this.description,
      selected: selected ?? this.selected,
    );
  }
}
