/// A user-visible category that can be attached to a [Reminder].
///
/// Tags are persisted in their own `tags` table (see
/// [TagRepository]) and are referenced by `reminders.tag_id`. The
/// "已完成" (completed) pseudo-tag is a real tag row with the
/// reserved id [kCompletedTagId]; [Reminder.isCompleted] is just a
/// thin getter over `tagId == kCompletedTagId` so the complete
/// behaviour flows through the same tag machinery as everything else.
///
/// Built-in tags (`builtIn == true`) are seeded once by the v5
/// migration and cannot be deleted, renamed, or recoloured. The
/// `TagsViewModel` mutators are no-ops for built-ins; the UI hides
/// the controls.
class Tag {
  const Tag({
    required this.id,
    required this.name,
    required this.color,
    this.builtIn = false,
    this.sortOrder = 0,
  });

  /// Reserved id for the "已完成" pseudo-tag. Used by
  /// [Reminder.isCompleted] and by the AI prompt to tell the model
  /// which id means "this reminder is already done".
  static const String completedId = '__completed__';

  /// Reserved id prefix for the four default user tags. The
  /// underscore-bracketed form guarantees the reserved ids can
  /// never collide with UUID4 custom-tag ids.
  static const String defaultIdPrefix = '__tag_default_';

  /// The four defaults the v5 migration seeds for fresh installs.
  /// Kept in code (not in the DB) so the UI can render stable
  /// human-readable names and the colour palette matches the
  /// Material 3 tokens the rest of the app uses.
  static const List<Tag> defaultTags = <Tag>[
    Tag(
      id: '${defaultIdPrefix}work__',
      name: '工作',
      color: 0xFF1E88E5, // Material blue 600
      builtIn: true,
      sortOrder: 0,
    ),
    Tag(
      id: '${defaultIdPrefix}life__',
      name: '生活',
      color: 0xFF43A047, // Material green 600
      builtIn: true,
      sortOrder: 1,
    ),
    Tag(
      id: '${defaultIdPrefix}study__',
      name: '学习',
      color: 0xFFFB8C00, // Material orange 600
      builtIn: true,
      sortOrder: 2,
    ),
    Tag(
      id: '${defaultIdPrefix}fun___',
      name: '娱乐',
      color: 0xFFE53935, // Material red 500
      builtIn: true,
      sortOrder: 3,
    ),
    Tag(
      id: completedId,
      name: '已完成',
      color: 0xFF757575, // Material grey 600
      builtIn: true,
      sortOrder: 100,
    ),
  ];

  /// Stable identifier. Built-in tags use reserved, underscore-
  /// bracketed ids; custom tags use a UUID4 generated by the
  /// view model.
  final String id;

  /// User-visible name. Validated to 1-12 Chinese characters at
  /// write time by [TagsViewModel].
  final String name;

  /// The tag's representative color, stored as an ARGB int so the
  /// model has no Flutter dependency and round-trips cleanly through
  /// the database.
  final int color;

  /// True for the seeded defaults + the "已完成" pseudo-tag. The
  /// view-model mutators refuse to change a built-in tag.
  final bool builtIn;

  /// Stable user-visible order. Lower comes first. Built-ins use
  /// the values in [defaultTags]; custom tags get `0` (which means
  /// they render after the first built-in, but the settings subpage
  /// groups them under a "自定义标签" header).
  final int sortOrder;

  Tag copyWith({String? name, int? color, int? sortOrder}) {
    return Tag(
      id: id,
      name: name ?? this.name,
      color: color ?? this.color,
      builtIn: builtIn,
      sortOrder: sortOrder ?? this.sortOrder,
    );
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
    'id': id,
    'name': name,
    'color': color,
    'built_in': builtIn,
    'sort_order': sortOrder,
  };

  factory Tag.fromJson(Map<String, dynamic> json) {
    return Tag(
      id: json['id'] as String,
      name: json['name'] as String,
      color: (json['color'] as num).toInt(),
      builtIn: json['built_in'] == true,
      sortOrder: (json['sort_order'] as num?)?.toInt() ?? 0,
    );
  }

  Map<String, dynamic> toMap() => <String, dynamic>{
    'id': id,
    'name': name,
    'color': color,
    'built_in': builtIn ? 1 : 0,
    'sort_order': sortOrder,
  };

  factory Tag.fromMap(Map<String, dynamic> map) {
    return Tag(
      id: map['id'] as String,
      name: map['name'] as String,
      // SQLite INTEGER arrives as `int`; defensive parse covers
      // hand-edited rows.
      color: (map['color'] as num).toInt(),
      builtIn: () {
        final v = map['built_in'];
        if (v is bool) return v;
        if (v is int) return v != 0;
        return false;
      }(),
      sortOrder: (map['sort_order'] as num?)?.toInt() ?? 0,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is Tag &&
      other.id == id &&
      other.name == name &&
      other.color == color &&
      other.builtIn == builtIn &&
      other.sortOrder == sortOrder;

  @override
  int get hashCode => Object.hash(id, name, color, builtIn, sortOrder);
}

/// Shorter alias that re-exports the reserved id so callers can
/// `import 'package:nousmind/models/tag.dart' show kCompletedTagId;`
/// without the `Tag.` prefix.
const String kCompletedTagId = Tag.completedId;

/// 15-color palette shared by the tag settings subpage and the
/// editor's "新建标签" inline dialog. Tones picked to be visually
/// distinguishable in both light and dark themes; ordering is
/// rainbow-ish for easy scanning.
const List<int> kTagPalette = <int>[
  0xFFEF5350, // red 400
  0xFFEC407A, // pink 400
  0xFFAB47BC, // purple 400
  0xFF7E57C2, // deep purple 400
  0xFF5C6BC0, // indigo 400
  0xFF42A5F5, // blue 400
  0xFF29B6F6, // light blue 400
  0xFF26C6DA, // cyan 400
  0xFF26A69A, // teal 400
  0xFF66BB6A, // green 400
  0xFF9CCC65, // light green 400
  0xFFFFCA28, // amber 400
  0xFFFFA726, // orange 400
  0xFF8D6E63, // brown 400
  0xFF78909C, // blue grey 400
];
